// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	httpx "github.com/quiby-ai/common/pkg/httpx"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, req
func (_m *Client) Do(ctx context.Context, req httpx.Request) (httpx.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 httpx.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, httpx.Request) (httpx.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, httpx.Request) httpx.Response); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(httpx.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, httpx.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DoGET provides a mock function with given fields: ctx, rawURL, params, headers
func (_m *Client) DoGET(ctx context.Context, rawURL string, params map[string]string, headers map[string]string) (httpx.Response, error) {
	ret := _m.Called(ctx, rawURL, params, headers)

	if len(ret) == 0 {
		panic("no return value specified for DoGET")
	}

	var r0 httpx.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, map[string]string) (httpx.Response, error)); ok {
		return rf(ctx, rawURL, params, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, map[string]string) httpx.Response); ok {
		r0 = rf(ctx, rawURL, params, headers)
	} else {
		r0 = ret.Get(0).(httpx.Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string, map[string]string) error); ok {
		r1 = rf(ctx, rawURL, params, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
